import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import uuid
import random
from decimal import Decimal
from datetime import datetime, timezone

from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker, AsyncSession
from sqlalchemy import select

from app.shared.database.base import Base
from app.modules.product.models import Brand, Category, Product, ProductImage, ProductVariant
from app.modules.inventory.models import Inventory, Warehouse

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql+asyncpg://postgres:postgres@localhost:5432/auraskincare",
)

IMAGE_BASE = "https://images.unsplash.com/photo"

engine = create_async_engine(DATABASE_URL, echo=False)
session_factory = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

BRANDS = [
    {"name": "CeraVe", "slug": "cerave", "description": "Dermatologist-developed skincare with essential ceramides."},
    {"name": "COSRX", "slug": "cosrx", "description": "Korean skincare essentials rooted in science."},
    {"name": "La Roche-Posay", "slug": "la-roche-posay", "description": "French pharmacy skincare for sensitive skin."},
    {"name": "Beauty of Joseon", "slug": "beauty-of-joseon", "description": "Hanbang-inspired modern Korean skincare."},
    {"name": "The Ordinary", "slug": "the-ordinary", "description": "Clinical skincare with transparent pricing."},
    {"name": "Anua", "slug": "anua", "description": "Korean clean skincare powered by nature."},
    {"name": "Cetaphil", "slug": "cetaphil", "description": "Gentle skincare trusted by dermatologists."},
    {"name": "Bioderma", "slug": "bioderma", "description": "French skincare biology for all skin types."},
]

CATEGORIES = [
    {"name": "Cleanser", "slug": "cleanser", "description": "Gentle cleansers for every skin type."},
    {"name": "Face Wash", "slug": "face-wash", "description": "Deep-cleansing face washes."},
    {"name": "Serum", "slug": "serum", "description": "Concentrated active serums."},
    {"name": "Toner", "slug": "toner", "description": "Balancing and hydrating toners."},
    {"name": "Moisturizer", "slug": "moisturizer", "description": "Daily moisturizers for all skin types."},
    {"name": "Sunscreen", "slug": "sunscreen", "description": "Broad-spectrum sun protection."},
    {"name": "Eye Cream", "slug": "eye-cream", "description": "Targeted eye treatments."},
    {"name": "Mask", "slug": "mask", "description": "Sheet masks and wash-off masks."},
    {"name": "Lip Care", "slug": "lip-care", "description": "Lip balms and treatments."},
    {"name": "Body Care", "slug": "body-care", "description": "Luxurious body moisturizers and oils."},
    {"name": "Hair Care", "slug": "hair-care", "description": "Scalp and hair treatments."},
    {"name": "Acne Care", "slug": "acne-care", "description": "Acne-prone skin solutions."},
]

PRODUCTS = [
    {
        "name": "Hydrating Cleanser",
        "slug": "cerave-hydrating-cleanser",
        "sku": "CER-CLN-001",
        "short_description": "Gentle, non-foaming cleanser for normal to dry skin.",
        "description": "A gentle, non-foaming cleanser that effectively removes dirt, oil, and makeup without disrupting the skin's natural protective barrier. Formulated with three essential ceramides and hyaluronic acid.",
        "price": Decimal("14.99"),
        "compare_price": Decimal("18.99"),
        "stock_quantity": 150,
        "status": "active",
        "is_featured": True,
        "is_bestseller": True,
        "is_new_arrival": False,
        "ingredients": "Water, Glycerin, Ceramide NP, Ceramide AP, Ceramide EOP, Hyaluronic Acid, Cetearyl Alcohol, Stearyl Alcohol.",
        "directions": "Apply to wet skin with gentle circular motions. Rinse thoroughly with lukewarm water. Use morning and evening.",
        "benefits": "Hydrates while cleansing, maintains skin barrier, suitable for dry and sensitive skin.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Low pH Good Morning Gel Cleanser",
        "slug": "cosrx-low-ph-cleanser",
        "sku": "COS-CLN-001",
        "short_description": "Low pH gel cleanser for morning use.",
        "description": "A mild, low-pH gel cleanser formulated with tea tree oil and BHA to gently exfoliate and cleanse without stripping moisture.",
        "price": Decimal("16.00"),
        "compare_price": Decimal("20.00"),
        "stock_quantity": 120,
        "status": "active",
        "is_featured": True,
        "is_bestseller": True,
        "is_new_arrival": False,
        "ingredients": "Water, Tea Tree Leaf Water, Salicylic Acid, Glycerin, Betaine.",
        "directions": "Apply a small amount to wet face, massage gently, and rinse with lukewarm water.",
        "benefits": "Exfoliates gently, controls sebum, maintains skin's optimal pH.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Toleriane Hydrating Gentle Cleanser",
        "slug": "la-roche-posay-toleriane-cleanser",
        "sku": "LRP-CLN-001",
        "short_description": "Hydrating cleanser for sensitive skin.",
        "description": "A milky, hydrating cleanser that removes makeup and impurities while soothing sensitive skin. Formulated with niacinamide and ceramide NP.",
        "price": Decimal("19.99"),
        "compare_price": Decimal("24.99"),
        "stock_quantity": 100,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Water, Glycerin, Niacinamide, Ceramide NP, Shea Butter.",
        "directions": "Massage onto damp skin. Rinse thoroughly. Avoid eye area.",
        "benefits": "Soothes sensitive skin, hydrates, removes makeup effectively.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Glow Serum: Rejuvenating + Brightening",
        "slug": "beauty-of-joseon-glow-serum",
        "sku": "BOJ-SER-001",
        "short_description": "Brightening serum with hanbang ingredients.",
        "description": "A lightweight, glow-boosting serum powered by 3% Tranexamic Acid and 2% Niacinamide, enriched with traditional Korean herbs.",
        "price": Decimal("22.00"),
        "compare_price": Decimal("28.00"),
        "stock_quantity": 90,
        "status": "active",
        "is_featured": True,
        "is_bestseller": True,
        "is_new_arrival": False,
        "ingredients": "Tranexamic Acid, Niacinamide, Ginseng Root Extract, Lotus Extract.",
        "directions": "Apply 2-3 drops onto face after toner. Pat gently until absorbed.",
        "benefits": "Brightens skin tone, fades dark spots, improves radiance.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Niacinamide 10% + Zinc 1%",
        "slug": "the-ordinary-niacinamide",
        "sku": "TO-SER-001",
        "short_description": "High-strength niacinamide serum.",
        "description": "A powerful serum combining 10% Niacinamide and 1% Zinc PCA to target visible skin concerns and support overall skin health.",
        "price": Decimal("8.90"),
        "compare_price": Decimal("12.00"),
        "stock_quantity": 200,
        "status": "active",
        "is_featured": True,
        "is_bestseller": True,
        "is_new_arrival": False,
        "ingredients": "Aqua, Niacinamide, Pentylene Glycol, Zinc PCA, Dimethyl Isosorbide.",
        "directions": "Apply to face morning and evening. Avoid eye area.",
        "benefits": "Reduces pore appearance, regulates sebum, brightens skin.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "DREAMING SUNSCREEN SPF 50+",
        "slug": "anua-sunscreen",
        "sku": "ANU-SUN-001",
        "short_description": "Lightweight daily sunscreen.",
        "description": "A lightweight, non-greasy sunscreen with SPF 50+ protection. Infused with Aloe Vera and Green Tea extract.",
        "price": Decimal("21.00"),
        "compare_price": Decimal("26.00"),
        "stock_quantity": 130,
        "status": "active",
        "is_featured": True,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Water, Aloe Vera, Green Tea Extract, Zinc Oxide, Titanium Dioxide.",
        "directions": "Apply generously 15 minutes before sun exposure. Reapply every 2 hours.",
        "benefits": "Broad-spectrum SPF 50+, lightweight, no white cast.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Moisturizing Cream for Dry Skin",
        "slug": "cetaphil-moisturizing-cream",
        "sku": "CET-MOI-001",
        "short_description": "Rich moisturizer for very dry skin.",
        "description": "A luxuriously rich moisturizer that clinically proven to provide immediate and long-lasting hydration for very dry skin.",
        "price": Decimal("17.99"),
        "compare_price": Decimal("22.00"),
        "stock_quantity": 140,
        "status": "active",
        "is_featured": False,
        "is_bestseller": True,
        "is_new_arrival": False,
        "ingredients": "Water, Glycerin, Petrolatum, Dimethicone, Niacinamide.",
        "directions": "Apply to dry skin as needed, especially after bathing.",
        "benefits": "Intensely hydrates, strengthens skin barrier, fragrance-free.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Sensibio H2O Micellar Water",
        "slug": "bioderma-sensibio-h2o",
        "sku": "BIO-CLN-001",
        "short_description": "Micellar water for sensitive skin.",
        "description": "The original micellar water that cleanses and removes makeup without rinsing. Perfect for sensitive skin.",
        "price": Decimal("16.50"),
        "compare_price": Decimal("20.00"),
        "stock_quantity": 160,
        "status": "active",
        "is_featured": True,
        "is_bestseller": True,
        "is_new_arrival": False,
        "ingredients": "Water, Poloxamer 184, Decyl Glucoside, Cucumber Fruit Extract.",
        "directions": "Soak a cotton pad and gently wipe over face and eyes. No rinsing needed.",
        "benefits": "Removes makeup, cleanses, soothes sensitive skin.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Hydrating Toner",
        "slug": "cerave-hydrating-toner",
        "sku": "CER-TON-001",
        "short_description": "Hydrating toner with hyaluronic acid.",
        "description": "An alcohol-free toner that hydrates and refreshes skin while helping to restore the protective skin barrier.",
        "price": Decimal("15.99"),
        "compare_price": Decimal("19.99"),
        "stock_quantity": 110,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Water, Glycerin, Hyaluronic Acid, Ceramide NP, Ceramide AP.",
        "directions": "Apply to face with cotton pad or hands after cleansing.",
        "benefits": "Hydrates, preps skin for next steps, alcohol-free.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Advanced Snail 96 Mucin Power Essence",
        "slug": "cosrx-snail-essence",
        "sku": "COS-SER-002",
        "short_description": "Snail mucin essence for repair and hydration.",
        "description": "A powerful essence containing 96% snail mucin to repair damaged skin, improve elasticity, and provide deep hydration.",
        "price": Decimal("24.00"),
        "compare_price": Decimal("30.00"),
        "stock_quantity": 80,
        "status": "active",
        "is_featured": True,
        "is_bestseller": True,
        "is_new_arrival": False,
        "ingredients": "Snail Secretion Filtrate, Betaine, Sodium Hyaluronate.",
        "directions": "Apply after toner, before moisturizer. Pat gently for absorption.",
        "benefits": "Repairs skin barrier, hydrates, improves elasticity.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Cicaplast B5+",
        "slug": "la-roche-posay-cicaplast",
        "sku": "LRP-SER-001",
        "short_description": "Soothing and repairing balm.",
        "description": "A multi-purpose soothing and repairing balm formulated with 5% Panthenol and Madecassoside to support skin recovery.",
        "price": Decimal("21.99"),
        "compare_price": Decimal("27.00"),
        "stock_quantity": 95,
        "status": "active",
        "is_featured": True,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Water, Panthenol, Madecassoside, Glycerin, Shea Butter.",
        "directions": "Apply a thin layer to clean skin as needed.",
        "benefits": "Soothes irritation, repairs skin barrier, reduces redness.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Red Blemish Spot Cream",
        "slug": "beauty-of-joseon-spot-cream",
        "sku": "BOJ-CRM-001",
        "short_description": "Targeted spot treatment for blemishes.",
        "description": "A concentrated spot treatment featuring 70% Artemisia and 5% Niacinamide to calm redness and fade blemishes.",
        "price": Decimal("19.00"),
        "compare_price": Decimal("24.00"),
        "stock_quantity": 85,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Artemisia, Niacinamide, Zinc PCA, Adenosine.",
        "directions": "Apply a small amount to blemishes after cleansing.",
        "benefits": "Reduces redness, fades dark spots, calms irritation.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Hyaluronic Acid 2% + B5",
        "slug": "the-ordinary-hyaluronic-acid",
        "sku": "TO-SER-002",
        "short_description": "Hydrating serum with multi-weight hyaluronic acid.",
        "description": "A hydrating serum formulated with multiple weights of hyaluronic acid and Vitamin B5 to provide multi-depth hydration.",
        "price": Decimal("9.80"),
        "compare_price": Decimal("13.00"),
        "stock_quantity": 180,
        "status": "active",
        "is_featured": True,
        "is_bestseller": True,
        "is_new_arrival": False,
        "ingredients": "Water, Sodium Hyaluronate, Panthenol, Glycerin.",
        "directions": "Apply to face morning and evening before moisturizer.",
        "benefits": "Deep hydration, plumps skin, improves skin texture.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Dark Spot Correcting Sunscreen SPF50+",
        "slug": "anua-dark-spot-sunscreen",
        "sku": "ANU-SUN-002",
        "short_description": "Brightening sunscreen with Niacinamide.",
        "description": "A lightweight sunscreen with SPF50+ protection, enriched with Niacinamide and Tranexamic Acid to correct dark spots.",
        "price": Decimal("24.00"),
        "compare_price": Decimal("30.00"),
        "stock_quantity": 100,
        "status": "active",
        "is_featured": True,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Water, Niacinamide, Tranexamic Acid, Zinc Oxide, Titanium Dioxide.",
        "directions": "Apply generously as the final step of your routine.",
        "benefits": "SPF50+, brightens, corrects dark spots, lightweight.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Ointment for Extremely Dry Skin",
        "slug": "cetaphil-ointment",
        "sku": "CET-MOI-002",
        "short_description": "Protective ointment for extra dry skin.",
        "description": "A premium ointment that provides long-lasting relief for extra dry, sensitive skin. Ideal for use on hands, feet, and lips.",
        "price": Decimal("13.99"),
        "compare_price": Decimal("17.00"),
        "stock_quantity": 120,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": False,
        "ingredients": "Petrolatum, Mineral Oil, Ceramide NP, Glycerin.",
        "directions": "Apply to affected areas as needed.",
        "benefits": "Intensive moisture barrier protection, fragrance-free.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Double Action Anti-Blemish Gel",
        "slug": "bioderma-anti-blemish-gel",
        "sku": "BIO-ACN-001",
        "short_description": "Targeted anti-blemish treatment.",
        "description": "A dual-action gel that targets blemishes and prevents new ones from forming. Suitable for acne-prone skin.",
        "price": Decimal("20.00"),
        "compare_price": Decimal("25.00"),
        "stock_quantity": 90,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": False,
        "ingredients": "Salicylic Acid, Glycolic Acid, Zinc PCA, Niacinamide.",
        "directions": "Apply to affected areas once or twice daily.",
        "benefits": "Reduces blemishes, prevents breakouts, controls oil.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Facial Foaming Gel",
        "slug": "cerave-foaming-gel",
        "sku": "CER-CLN-002",
        "short_description": "Foaming gel cleanser for normal to oily skin.",
        "description": "A foaming gel cleanser that removes excess oil and dirt without disrupting the skin's protective barrier.",
        "price": Decimal("15.99"),
        "compare_price": Decimal("19.99"),
        "stock_quantity": 130,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": False,
        "ingredients": "Water, Glycerin, Ceramide NP, Niacinamide, Salicylic Acid.",
        "directions": "Massage onto wet skin. Rinse thoroughly.",
        "benefits": "Deep cleanses, controls oil, maintains barrier.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Advanced Brightening Toner",
        "slug": "cosrx-advanced-toner",
        "sku": "COS-TON-001",
        "short_description": "Brightening toner with Galactomyces.",
        "description": "A brightening toner containing 97% Galactomyces Ferment Filtrate to refine skin texture and improve radiance.",
        "price": Decimal("23.00"),
        "compare_price": Decimal("28.00"),
        "stock_quantity": 75,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Galactomyces Ferment Filtrate, Niacinamide, Panthenol.",
        "directions": "Apply after cleansing with cotton pad or hands.",
        "benefits": "Brightens, refines texture, improves clarity.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Effaclar Purifying Foaming Gel",
        "slug": "la-roche-posay-effaclar",
        "sku": "LRP-CLN-002",
        "short_description": "Purifying cleanser for oily, blemish-prone skin.",
        "description": "A high-tolerance foaming gel that purifies and cleanses oily, blemish-prone skin without over-drying.",
        "price": Decimal("18.99"),
        "compare_price": Decimal("23.00"),
        "stock_quantity": 110,
        "status": "active",
        "is_featured": False,
        "is_bestseller": True,
        "is_new_arrival": False,
        "ingredients": "Water, Glycerin, Salicylic Acid, Zinc PCA, Lactic Acid.",
        "directions": "Apply to wet skin, massage, and rinse with lukewarm water.",
        "benefits": "Purifies, reduces excess sebum, prevents breakouts.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Glow Deep: Niacinamide + Rice Water",
        "slug": "beauty-of-joseon-glow-deep",
        "sku": "BOJ-SER-002",
        "short_description": "Niacinamide serum with rice water.",
        "description": "A brightening serum combining 2% Niacinamide and 68% Rice Water to even skin tone and impart a natural glow.",
        "price": Decimal("20.00"),
        "compare_price": Decimal("25.00"),
        "stock_quantity": 95,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": False,
        "ingredients": "Niacinamide, Rice Water, Alpha-Arbutin, Panthenol.",
        "directions": "Apply 2-3 drops after toner, pat until absorbed.",
        "benefits": "Brightens, evens tone, improves texture.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Vitamin C Suspension 23% + HA Spheres 2%",
        "slug": "the-ordinary-vitamin-c",
        "sku": "TO-SER-003",
        "short_description": "High-strength Vitamin C serum.",
        "description": "A potent Vitamin C suspension with 23% L-Ascorbic Acid and 2% Hyaluronic Acid spheres for brightening and antioxidant protection.",
        "price": Decimal("10.80"),
        "compare_price": Decimal("14.00"),
        "stock_quantity": 150,
        "status": "active",
        "is_featured": True,
        "is_bestseller": True,
        "is_new_arrival": False,
        "ingredients": "L-Ascorbic Acid, Hyaluronic Acid, Glycerin.",
        "directions": "Apply a small amount to clean skin before moisturizer.",
        "benefits": "Brightens, fades dark spots, antioxidant protection.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Heartleaf Pore Control Cleansing Oil",
        "slug": "anua-cleansing-oil",
        "sku": "ANU-CLN-001",
        "short_description": "Oil cleanser for deep pore cleansing.",
        "description": "A lightweight cleansing oil that dissolves makeup and impurities while controlling sebum and refining pores.",
        "price": Decimal("19.00"),
        "compare_price": Decimal("24.00"),
        "stock_quantity": 100,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Heartleaf Extract, Glycerin, Castor Oil, Jojoba Oil.",
        "directions": "Massage onto dry skin, emulsify with water, rinse thoroughly.",
        "benefits": "Dissolves makeup, controls sebum, refines pores.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Advanced Moisturizing Lotion",
        "slug": "cetaphil-advanced-moisturizer",
        "sku": "CET-MOI-003",
        "short_description": "Lightweight daily moisturizer.",
        "description": "A lightweight daily moisturizer that provides long-lasting hydration and helps strengthen the skin barrier.",
        "price": Decimal("16.99"),
        "compare_price": Decimal("21.00"),
        "stock_quantity": 140,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": False,
        "ingredients": "Water, Glycerin, Niacinamide, Ceramide NP, Dimethicone.",
        "directions": "Apply to face and neck morning and evening.",
        "benefits": "Hydrates, strengthens barrier, lightweight.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Hydrabio Gel-Creme",
        "slug": "bioderma-hydrabio",
        "sku": "BIO-MOI-001",
        "short_description": "Moisturizing gel-cream for dehydrated skin.",
        "description": "A refreshing gel-cream that provides intense hydration and improves skin radiance. Contains Derma Complex.",
        "price": Decimal("27.00"),
        "compare_price": Decimal("32.00"),
        "stock_quantity": 80,
        "status": "active",
        "is_featured": True,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Water, Glycerin, Salicylic Acid, Derma Complex, Mannitol.",
        "directions": "Apply to clean skin morning and evening.",
        "benefits": "Intense hydration, improves radiance, lightweight.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Moisturizing Cream Pump",
        "slug": "cerave-moisturizing-cream",
        "sku": "CER-MOI-001",
        "short_description": "Daily moisturizing cream for face and body.",
        "description": "A rich, non-greasy moisturizing cream with three essential ceramides and hyaluronic acid for face and body.",
        "price": Decimal("18.99"),
        "compare_price": Decimal("23.00"),
        "stock_quantity": 160,
        "status": "active",
        "is_featured": True,
        "is_bestseller": True,
        "is_new_arrival": False,
        "ingredients": "Water, Glycerin, Ceramide NP, Ceramide AP, Ceramide EOP, Hyaluronic Acid.",
        "directions": "Apply generously to face and body as needed.",
        "benefits": "24-hour hydration, strengthens barrier, fragrance-free.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "UV Protection SPF 50+ PA++++",
        "slug": "cosrx-uv-sunscreen",
        "sku": "COS-SUN-001",
        "short_description": "Lightweight Korean sunscreen.",
        "description": "A lightweight, non-greasy sunscreen with SPF50+ and PA++++ protection. No white cast, suitable for daily use.",
        "price": Decimal("20.00"),
        "compare_price": Decimal("25.00"),
        "stock_quantity": 120,
        "status": "active",
        "is_featured": False,
        "is_bestseller": True,
        "is_new_arrival": False,
        "ingredients": "Water, Zinc Oxide, Titanium Dioxide, Glycerin, Aloe Vera.",
        "directions": "Apply as the final step of your morning routine.",
        "benefits": "SPF50+, no white cast, lightweight.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Retinol B3 Serum",
        "slug": "la-roche-posay-retinol-b3",
        "sku": "LRP-SER-002",
        "short_description": "Anti-aging retinol serum with Vitamin B3.",
        "description": "A gentle retinol serum formulated with Vitamin B3 to target signs of aging while minimizing irritation.",
        "price": Decimal("39.99"),
        "compare_price": Decimal("49.99"),
        "stock_quantity": 70,
        "status": "active",
        "is_featured": True,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Retinol, Niacinamide, Glycerin, Shea Butter.",
        "directions": "Apply a pea-sized amount to face at night. Start with 2-3 times per week.",
        "benefits": "Reduces fine lines, improves texture, gentle formula.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Revival Serum: Ginseng + Snail Mucin",
        "slug": "beauty-of-joseon-revival",
        "sku": "BOJ-SER-003",
        "short_description": "Revitalizing serum with ginseng and snail mucin.",
        "description": "A revitalizing serum combining Ginseng extract and Snail Mucin to restore skin vitality and elasticity.",
        "price": Decimal("25.00"),
        "compare_price": Decimal("32.00"),
        "stock_quantity": 85,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Ginseng Root Extract, Snail Secretion Filtrate, Niacinamide.",
        "directions": "Apply 2-3 drops after toner, pat gently.",
        "benefits": "Revitalizes, improves elasticity, deeply hydrates.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "AHA 30% + BHA 2% Peeling Solution",
        "slug": "the-ordinary-aha-bha",
        "sku": "TO-EXF-001",
        "short_description": "Exfoliating peeling solution.",
        "description": "A high-strength exfoliating solution with 30% AHA and 2% BHA to target dullness, uneven texture, and congestion.",
        "price": Decimal("11.20"),
        "compare_price": Decimal("15.00"),
        "stock_quantity": 100,
        "status": "active",
        "is_featured": True,
        "is_bestseller": True,
        "is_new_arrival": False,
        "ingredients": "Glycolic Acid, Lactic Acid, Salicylic Acid, Tasmanian Pepperberry.",
        "directions": "Use once a week on clean, dry skin. Do not leave on for more than 10 minutes.",
        "benefits": "Exfoliates, improves texture, brightens.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Oatmeal Calming Serum",
        "slug": "anua-oatmeal-serum",
        "sku": "ANU-SER-001",
        "short_description": "Soothing serum with colloidal oatmeal.",
        "description": "A calming serum formulated with 70% colloidal oatmeal to soothe irritation and strengthen the skin barrier.",
        "price": Decimal("22.00"),
        "compare_price": Decimal("28.00"),
        "stock_quantity": 90,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Colloidal Oatmeal, Panthenol, Glycerin, Centella Asiatica.",
        "directions": "Apply after toner, before moisturizer.",
        "benefits": "Soothes irritation, strengthens barrier, hydrates.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Radiance Renewal Cream",
        "slug": "cetaphill-radiance-cream",
        "sku": "CET-MOI-004",
        "short_description": "Brightening moisturizer with Vitamin C.",
        "description": "A brightening daily moisturizer with Vitamin C and peptides to improve radiance and firmness.",
        "price": Decimal("21.99"),
        "compare_price": Decimal("27.00"),
        "stock_quantity": 85,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": False,
        "ingredients": "Water, Glycerin, Ascorbic Acid, Peptides, Ceramide NP.",
        "directions": "Apply to face and neck morning and evening.",
        "benefits": "Brightens, firms, improves elasticity.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Sebium Pore Refiner",
        "slug": "bioderma-sebium",
        "sku": "BIO-POR-001",
        "short_description": "Pore refining treatment for oily skin.",
        "description": "A pore-refining treatment that reduces the appearance of enlarged pores and controls excess sebum.",
        "price": Decimal("24.00"),
        "compare_price": Decimal("29.00"),
        "stock_quantity": 75,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": False,
        "ingredients": "Water, Glycerin, Salicylic Acid, Zinc PCA, Lactic Acid.",
        "directions": "Apply to clean skin morning and evening.",
        "benefits": "Refines pores, controls oil, smooths texture.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Healing Ointment",
        "slug": "cerave-healing-ointment",
        "sku": "CER-MOI-002",
        "short_description": "Protective ointment for extra dry skin.",
        "description": "An ultra-rich ointment that provides a protective barrier for extra dry, rough, and sensitive skin.",
        "price": Decimal("13.99"),
        "compare_price": Decimal("17.00"),
        "stock_quantity": 130,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": False,
        "ingredients": "Petrolatum, Mineral Oil, Ceramide NP, Glycerin.",
        "directions": "Apply to affected areas as needed.",
        "benefits": "Intensive protection, heals dry skin, fragrance-free.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Eye Repair Cream",
        "slug": "cerave-eye-repair",
        "sku": "CER-EYE-001",
        "short_description": "Hydrating eye cream for dark circles.",
        "description": "A hydrating eye cream that reduces the appearance of dark circles and puffiness while strengthening the delicate eye area.",
        "price": Decimal("19.99"),
        "compare_price": Decimal("24.99"),
        "stock_quantity": 100,
        "status": "active",
        "is_featured": True,
        "is_bestseller": False,
        "is_new_arrival": False,
        "ingredients": "Water, Glycerin, Hyaluronic Acid, Ceramide NP, Peptides.",
        "directions": "Gently pat around eye area morning and evening.",
        "benefits": "Reduces dark circles, hydrates, reduces puffiness.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Glass Skin Mask",
        "slug": "cosrx-glass-mask",
        "sku": "COS-MSK-001",
        "short_description": "Sheet mask for glass skin effect.",
        "description": "A luxurious sheet mask infused with Hyaluronic Acid and Snail Mucin to deliver an instant glass skin effect.",
        "price": Decimal("6.00"),
        "compare_price": Decimal("8.00"),
        "stock_quantity": 200,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Snail Mucin, Hyaluronic Acid, Glycerin, Allantoin.",
        "directions": "Apply to clean skin for 15-20 minutes. Remove and pat in excess essence.",
        "benefits": "Instant hydration, glowing skin, plumps.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Ultra-Lip Balm SPF 50",
        "slug": "la-roche-posay-lip-balm",
        "sku": "LRP-LIP-001",
        "short_description": "Protective lip balm with SPF.",
        "description": "A protective lip balm with SPF 50 that hydrates and protects delicate lip skin from UV damage.",
        "price": Decimal("9.99"),
        "compare_price": Decimal("12.99"),
        "stock_quantity": 150,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": False,
        "ingredients": "Shea Butter, Beeswax, Zinc Oxide, Vitamin E.",
        "directions": "Apply liberally to lips as needed.",
        "benefits": "SPF 50 protection, hydrates, prevents chapping.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Ginseng Sleeping Mask",
        "slug": "beauty-of-joseon-sleeping-mask",
        "sku": "BOJ-MSK-001",
        "short_description": "Overnight sleeping mask with ginseng.",
        "description": "An overnight sleeping mask enriched with Ginseng and Honey to nourish and rejuvenate skin while you sleep.",
        "price": Decimal("24.00"),
        "compare_price": Decimal("30.00"),
        "stock_quantity": 70,
        "status": "active",
        "is_featured": True,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Ginseng Root Extract, Honey, Niacinamide, Hyaluronic Acid.",
        "directions": "Apply as the last step of your evening routine. Leave on overnight.",
        "benefits": "Nourishes, rejuvenates, improves elasticity.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Multi-Active Brightening Toner",
        "slug": "the-ordinary-toner",
        "sku": "TO-TON-001",
        "short_description": "Exfoliating toner with Glycolic Acid.",
        "description": "An exfoliating toner with 7% Glycolic Acid to improve skin texture and radiance.",
        "price": Decimal("11.20"),
        "compare_price": Decimal("15.00"),
        "stock_quantity": 110,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": False,
        "ingredients": "Water, Glycolic Acid, Eucalyptus, Ginseng Root.",
        "directions": "Apply with cotton pad to clean skin. Use in the evening.",
        "benefits": "Exfoliates, improves texture, brightens.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Water Bank Cream",
        "slug": "anua-waterbank-cream",
        "sku": "ANU-MOI-001",
        "short_description": "Intensive hydrating cream.",
        "description": "An intensive hydrating cream with Water Bank technology to provide long-lasting moisture for dehydrated skin.",
        "price": Decimal("28.00"),
        "compare_price": Decimal("35.00"),
        "stock_quantity": 80,
        "status": "active",
        "is_featured": True,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Water, Glycerin, Hyaluronic Acid, Ceramide NP, Shea Butter.",
        "directions": "Apply to face and neck morning and evening.",
        "benefits": "Intense hydration, strengthens barrier, long-lasting moisture.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Cica-Face Cream",
        "slug": "cetaphil-cica-cream",
        "sku": "CET-CRM-001",
        "short_description": "Soothing cica cream for sensitive skin.",
        "description": "A soothing cream with Cica (Centella Asiatica) to calm irritated and sensitive skin.",
        "price": Decimal("19.99"),
        "compare_price": Decimal("24.99"),
        "stock_quantity": 90,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Centella Asiatica, Panthenol, Glycerin, Ceramide NP.",
        "directions": "Apply to face as needed for soothing relief.",
        "benefits": "Soothes irritation, calms redness, strengthens barrier.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Eye Contour Gel",
        "slug": "bioderma-eye-gel",
        "sku": "BIO-EYE-001",
        "short_description": "Cooling eye contour gel.",
        "description": "A cooling eye contour gel that reduces puffiness and dark circles while hydrating the delicate eye area.",
        "price": Decimal("26.00"),
        "compare_price": Decimal("32.00"),
        "stock_quantity": 70,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": False,
        "ingredients": "Water, Glycerin, Caffeine, Vitamin C, Hyaluronic Acid.",
        "directions": "Gently pat around eye area morning and evening.",
        "benefits": "Reduces puffiness, fades dark circles, hydrates.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Retinol Serum 0.3%",
        "slug": "cerave-retinol-serum",
        "sku": "CER-SER-001",
        "short_description": "Gentle retinol serum for anti-aging.",
        "description": "A gentle retinol serum formulated with 0.3% retinol and ceramides to target signs of aging without irritation.",
        "price": Decimal("24.99"),
        "compare_price": Decimal("29.99"),
        "stock_quantity": 80,
        "status": "active",
        "is_featured": True,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Retinol, Ceramide NP, Ceramide AP, Niacinamide, Glycerin.",
        "directions": "Apply a small amount to face at night. Start with 2-3 times per week.",
        "benefits": "Reduces fine lines, improves texture, gentle formula.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Advanced Snail 92 Cream",
        "slug": "cosrx-snail-cream",
        "sku": "COS-CRM-001",
        "short_description": "Moisturizing cream with 92% snail mucin.",
        "description": "A deeply hydrating moisturizer with 92% snail mucin to repair and revitalize skin.",
        "price": Decimal("25.00"),
        "compare_price": Decimal("32.00"),
        "stock_quantity": 90,
        "status": "active",
        "is_featured": True,
        "is_bestseller": True,
        "is_new_arrival": False,
        "ingredients": "Snail Secretion Filtrate, Glycerin, Betaine, Allantoin.",
        "directions": "Apply to face and neck morning and evening.",
        "benefits": "Deeply hydrates, repairs, improves elasticity.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Micellar Water Sensitive Skin",
        "slug": "bioderma-micellar-water",
        "sku": "BIO-CLN-002",
        "short_description": "Micellar water for sensitive skin.",
        "description": "A gentle micellar water that removes makeup and impurities while soothing sensitive skin.",
        "price": Decimal("14.50"),
        "compare_price": Decimal("18.00"),
        "stock_quantity": 140,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": False,
        "ingredients": "Water, Poloxamer 184, Decyl Glucoside, Cucumber Extract.",
        "directions": "Soak cotton pad and wipe over face and eyes.",
        "benefits": "Removes makeup, cleanses, soothes.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Clear Skin Spot Corrector",
        "slug": "anua-spot-corrector",
        "sku": "ANU-ACN-001",
        "short_description": "Spot treatment with 10% Niacinamide.",
        "description": "A potent spot treatment with 10% Niacinamide and Zinc PCA to clear blemishes and prevent new ones.",
        "price": Decimal("18.00"),
        "compare_price": Decimal("22.00"),
        "stock_quantity": 100,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Niacinamide, Zinc PCA, Salicylic Acid, Centella Asiatica.",
        "directions": "Apply to blemishes 1-2 times daily.",
        "benefits": "Clears blemishes, prevents breakouts, controls oil.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Barrier Repair Cream",
        "slug": "cetaphil-barrier-cream",
        "sku": "CET-CRM-002",
        "short_description": "Repair cream for compromised skin barrier.",
        "description": "A rich repair cream formulated with ceramides and niacinamide to restore and strengthen the skin barrier.",
        "price": Decimal("23.99"),
        "compare_price": Decimal("29.99"),
        "stock_quantity": 85,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": False,
        "ingredients": "Water, Glycerin, Ceramide NP, Niacinamide, Shea Butter.",
        "directions": "Apply to clean skin morning and evening.",
        "benefits": "Repairs barrier, hydrates, reduces sensitivity.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Exfoliating Foot Cream",
        "slug": "cetaphil-foot-cream",
        "sku": "CET-BOD-001",
        "short_description": "Intensive foot cream with exfoliating acids.",
        "description": "An intensive foot cream with Lactic Acid and Urea to exfoliate and moisturize rough, dry feet.",
        "price": Decimal("15.99"),
        "compare_price": Decimal("19.99"),
        "stock_quantity": 110,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": False,
        "ingredients": "Water, Glycerin, Lactic Acid, Urea, Shea Butter.",
        "directions": "Apply to clean, dry feet morning and evening.",
        "benefits": "Exfoliates, moisturizes, softens rough skin.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Scalp Relief Serum",
        "slug": "anua-scalp-serum",
        "sku": "ANU-HAI-001",
        "short_description": "Soothing scalp serum with Tea Tree.",
        "description": "A soothing scalp serum formulated with Tea Tree Oil and Salicylic Acid to relieve itchiness and flaking.",
        "price": Decimal("21.00"),
        "compare_price": Decimal("26.00"),
        "stock_quantity": 80,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Tea Tree Oil, Salicylic Acid, Glycerin, Panthenol.",
        "directions": "Apply directly to scalp 1-2 times daily.",
        "benefits": "Soothes scalp, reduces flaking, controls sebum.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Soothing Body Lotion",
        "slug": "cerave-body-lotion",
        "sku": "CER-BOD-001",
        "short_description": "Daily body lotion with ceramides.",
        "description": "A daily body lotion with three essential ceramides and hyaluronic acid to hydrate and strengthen the skin barrier.",
        "price": Decimal("16.99"),
        "compare_price": Decimal("20.00"),
        "stock_quantity": 150,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": False,
        "ingredients": "Water, Glycerin, Ceramide NP, Ceramide AP, Ceramide EOP, Hyaluronic Acid.",
        "directions": "Apply to body as needed, especially after bathing.",
        "benefits": "Hydrates, strengthens barrier, fragrance-free.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Hyaluronic Acid Serum",
        "slug": "the-ordinary-hyaluronic-acid-2",
        "sku": "TO-SER-004",
        "short_description": "Multi-weight hyaluronic acid serum.",
        "description": "A hydrating serum with multi-weight hyaluronic acid for deep, multi-depth hydration.",
        "price": Decimal("9.80"),
        "compare_price": Decimal("13.00"),
        "stock_quantity": 180,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": False,
        "ingredients": "Water, Sodium Hyaluronate, Glycerin, Panthenol.",
        "directions": "Apply to face morning and evening before moisturizer.",
        "benefits": "Deep hydration, plumps skin, improves texture.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Snail Mucin 92% Repair Cream",
        "slug": "cosrx-snail-repair-cream",
        "sku": "COS-CRM-002",
        "short_description": "Repair cream with 92% snail mucin.",
        "description": "A rich repair cream with 92% snail mucin to deeply nourish and repair damaged skin.",
        "price": Decimal("27.00"),
        "compare_price": Decimal("34.00"),
        "stock_quantity": 85,
        "status": "active",
        "is_featured": True,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Snail Secretion Filtrate, Glycerin, Betaine, Allantoin, Shea Butter.",
        "directions": "Apply to face and neck morning and evening.",
        "benefits": "Repairs, nourishes, deeply hydrates.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Acne Mark Clearing Serum",
        "slug": "anua-acne-serum",
        "sku": "ANU-SER-002",
        "short_description": "Clearing serum for acne marks.",
        "description": "A concentrated clearing serum with 5% Niacinamide and Zinc PCA to fade acne marks and prevent new breakouts.",
        "price": Decimal("20.00"),
        "compare_price": Decimal("25.00"),
        "stock_quantity": 95,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": False,
        "ingredients": "Niacinamide, Zinc PCA, Salicylic Acid, Centella Asiatica.",
        "directions": "Apply 2-3 drops after toner, pat gently.",
        "benefits": "Fades marks, prevents breakouts, controls oil.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Vitamin C Brightening Cream",
        "slug": "cetaphil-vitamin-c-cream",
        "sku": "CET-CRM-003",
        "short_description": "Brightening cream with Vitamin C.",
        "description": "A brightening daily moisturizer with 10% Vitamin C to improve radiance and even skin tone.",
        "price": Decimal("24.99"),
        "compare_price": Decimal("30.00"),
        "stock_quantity": 80,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": True,
        "ingredients": "Water, Glycerin, Ascorbic Acid, Ceramide NP, Peptides.",
        "directions": "Apply to face and neck morning and evening.",
        "benefits": "Brightens, evens tone, antioxidant protection.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Lip Sleeping Mask",
        "slug": "laneige-lip-mask",
        "sku": "LNL-LIP-001",
        "short_description": "Overnight lip mask for soft lips.",
        "description": "An overnight lip mask enriched with Vitamin C and antioxidants to hydrate and soften lips while you sleep.",
        "price": Decimal("22.00"),
        "compare_price": Decimal("28.00"),
        "stock_quantity": 100,
        "status": "active",
        "is_featured": True,
        "is_bestseller": False,
        "is_new_arrival": False,
        "ingredients": "Shea Butter, Beeswax, Vitamin C, Berry Extract.",
        "directions": "Apply generously to lips before bed.",
        "benefits": "Hydrates, softens, overnight treatment.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
    {
        "name": "Rose Hip Body Oil",
        "slug": "cetaphil-body-oil",
        "sku": "CET-BOD-002",
        "short_description": "Nourishing body oil with Rose Hip.",
        "description": "A nourishing body oil with Rose Hip and Jojoba to deeply moisturize and improve skin elasticity.",
        "price": Decimal("19.99"),
        "compare_price": Decimal("24.00"),
        "stock_quantity": 90,
        "status": "active",
        "is_featured": False,
        "is_bestseller": False,
        "is_new_arrival": False,
        "ingredients": "Rose Hip Oil, Jojoba Oil, Glycerin, Vitamin E.",
        "directions": "Apply to damp skin after showering.",
        "benefits": "Deeply moisturizes, improves elasticity, nourishes.",
        "thumbnail_url": f"{IMAGE_BASE}-1614814984609-58d4c0f2e5b7?w=600&h=600&fit=crop",
    },
]


async def get_or_create_brand(db: AsyncSession, brand_data: dict) -> Brand:
    result = await db.execute(select(Brand).where(Brand.slug == brand_data["slug"]))
    brand = result.scalar_one_or_none()
    if not brand:
        brand = Brand(**brand_data)
        db.add(brand)
        await db.flush()
    return brand


async def get_or_create_category(db: AsyncSession, category_data: dict) -> Category:
    result = await db.execute(select(Category).where(Category.slug == category_data["slug"]))
    category = result.scalar_one_or_none()
    if not category:
        category = Category(**category_data)
        db.add(category)
        await db.flush()
    return category


async def get_or_create_warehouse(db: AsyncSession) -> Warehouse:
    result = await db.execute(select(Warehouse).where(Warehouse.code == "WH-01"))
    warehouse = result.scalar_one_or_none()
    if not warehouse:
        warehouse = Warehouse(name="Main Warehouse", code="WH-01", location="Dhaka, Bangladesh", is_active=True)
        db.add(warehouse)
        await db.flush()
    return warehouse


async def seed() -> None:
    async with session_factory() as db:
        print("Starting seed...")

        brand_map = {}
        for brand_data in BRANDS:
            brand = await get_or_create_brand(db, brand_data)
            brand_map[brand.slug] = brand.id
            print(f"  Brand: {brand.name} ({brand.slug})")

        category_map = {}
        for category_data in CATEGORIES:
            category = await get_or_create_category(db, category_data)
            category_map[category.slug] = category.id
            print(f"  Category: {category.name} ({category.slug})")

        warehouse = await get_or_create_warehouse(db)
        print(f"  Warehouse: {warehouse.name} ({warehouse.code})")

        created_products = 0
        category_keywords = {
            "cleanser": "cleanser",
            "face wash": "face-wash",
            "foaming gel": "face-wash",
            "toner": "toner",
            "serum": "serum",
            "moisturizer": "moisturizer",
            "moisturising": "moisturizer",
            "cream": "moisturizer",
            "sunscreen": "sunscreen",
            "eye": "eye-cream",
            "mask": "mask",
            "lip": "lip-care",
            "body": "body-care",
            "hair": "hair-care",
            "acne": "acne-care",
            "spot": "acne-care",
            "clearing": "acne-care",
            "ointment": "body-care",
            "lotion": "body-care",
            "oil": "body-care",
            "balm": "lip-care",
            "sleeping": "mask",
            "sheet": "mask",
            "gel": "moisturizer",
            "essence": "serum",
            "ampoule": "serum",
            "peeling": "serum",
            "exfoliating": "serum",
            "brightening": "serum",
            "hydrating": "serum",
            "retinol": "serum",
            "vitamin c": "serum",
            "aha": "serum",
            "bha": "serum",
            "niacinamide": "serum",
            "hyaluronic": "serum",
            "snail": "serum",
            "ginseng": "serum",
            "cica": "serum",
            "centella": "serum",
            "salicylic": "acne-care",
            "zinc": "acne-care",
            "sulfate": "face-wash",
            "micellar": "cleanser",
            "oil": "body-care",
        }

        def guess_category(name: str, slug: str) -> str:
            lower = f"{name} {slug}".lower()
            for keyword, cat_slug in category_keywords.items():
                if keyword in lower:
                    return cat_slug
            return "moisturizer"

        for product_data in PRODUCTS:
            existing = await db.execute(select(Product).where(Product.slug == product_data["slug"]))
            if existing.scalar_one_or_none():
                continue

            brand_slug = product_data["slug"].split("-")[0]
            category_slug = guess_category(product_data["name"], product_data["slug"])

            brand_id = brand_map.get(brand_slug) or brand_map.get("cerave")
            category_id = category_map.get(category_slug) or category_map.get("skincare")

            product = Product(
                brand_id=brand_id,
                category_id=category_id,
                name=product_data["name"],
                slug=product_data["slug"],
                sku=product_data["sku"],
                short_description=product_data["short_description"],
                description=product_data["description"],
                status=product_data["status"],
                product_type="simple",
                price=product_data["price"],
                compare_at_price=product_data.get("compare_price"),
                currency="USD",
                stock_quantity=product_data["stock_quantity"],
                thumbnail_url=product_data["thumbnail_url"],
                is_featured=product_data.get("is_featured", False),
                is_active=True,
            )
            db.add(product)
            await db.flush()

            image = ProductImage(
                product_id=product.id,
                image_url=product_data["thumbnail_url"],
                alt_text=product_data["name"],
                sort_order=0,
                is_primary=True,
            )
            db.add(image)

            variant_count = random.randint(0, 2)
            for i in range(variant_count):
                variant = ProductVariant(
                    product_id=product.id,
                    name=f"Variant {i + 1}",
                    sku=f"{product_data['sku']}-V{i + 1}",
                    price=product_data["price"] + Decimal(str(i * 2)),
                    stock_quantity=random.randint(10, 50),
                    attributes={"size": f"{30 + i * 10}ml", "type": "variant"},
                    is_active=True,
                )
                db.add(variant)

            inventory = Inventory(
                product_id=product.id,
                warehouse_id=warehouse.id,
                quantity_on_hand=product_data["stock_quantity"],
                quantity_reserved=0,
                low_stock_threshold=10,
                is_tracking_enabled=True,
            )
            db.add(inventory)

            created_products += 1

        await db.commit()
        print(f"Seeded {created_products} products successfully.")


if __name__ == "__main__":
    import asyncio

    asyncio.run(seed())
