"""add order_number to orders

Revision ID: 28a4f978cc5d
Revises: feb39ceece7d
Create Date: 2026-09-17 11:11:53.995439
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "28a4f978cc5d"
down_revision: str | None = "feb39ceece7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("order_number", sa.String(length=50), nullable=False)
    )
    op.create_index(
        op.f("ix_orders_order_number"), "orders", ["order_number"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_order_number"), table_name="orders")
    op.drop_column("orders", "order_number")
    # ### end Alembic commands ###
