"""add payment module and notification updates

Revision ID: a7fc6d8fb412
Revises: 745c2e188c15
Create Date: 2026-09-22 22:02:56.908674
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = "a7fc6d8fb412"
down_revision: Union[str, None] = "745c2e188c15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_conversations_agent_type"), table_name="ai_conversations")
    op.add_column("ai_messages", sa.Column("extra_metadata", sa.Text(), nullable=True))
    op.drop_index(op.f("ix_ai_messages_role"), table_name="ai_messages")
    op.create_foreign_key(
        None, "ai_messages", "ai_conversations", ["conversation_id"], ["id"]
    )
    op.drop_column("ai_messages", "metadata")
    op.drop_index(op.f("ix_customers_status"), table_name="customers")
    op.drop_index(op.f("ix_customers_phone"), table_name="customers")
    op.create_index(op.f("ix_customers_phone"), "customers", ["phone"], unique=True)
    op.alter_column(
        "marketing_campaigns",
        "start_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "marketing_campaigns",
        "end_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.create_foreign_key(
        None, "marketing_contents", "marketing_templates", ["template_id"], ["id"]
    )
    op.create_foreign_key(
        None, "marketing_contents", "marketing_campaigns", ["campaign_id"], ["id"]
    )
    op.alter_column(
        "marketing_templates",
        "is_active",
        existing_type=sa.BOOLEAN(),
        type_=sa.String(length=10),
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.add_column(
        "notifications",
        sa.Column("retry_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "notifications",
        sa.Column("max_retries", sa.Integer(), nullable=False, server_default="3"),
    )
    op.add_column(
        "notifications", sa.Column("next_retry_at", sa.DateTime(), nullable=True)
    )
    op.alter_column(
        "notifications",
        "sent_at",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.DateTime(),
        existing_nullable=True,
        postgresql_using="sent_at::timestamp",
    )
    op.create_foreign_key(None, "order_events", "orders", ["order_id"], ["id"])
    op.add_column(
        "users", sa.Column("stripe_customer_id", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_users_stripe_customer_id"),
        "users",
        ["stripe_customer_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_stripe_customer_id"), table_name="users")
    op.drop_column("users", "stripe_customer_id")
    op.drop_constraint(None, "order_events", type_="foreignkey")
    op.alter_column(
        "notifications",
        "sent_at",
        existing_type=sa.DateTime(),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.drop_column("notifications", "next_retry_at")
    op.drop_column("notifications", "max_retries")
    op.drop_column("notifications", "retry_count")
    op.alter_column(
        "marketing_templates",
        "is_active",
        existing_type=sa.String(length=10),
        type_=sa.BOOLEAN(),
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.drop_constraint(None, "marketing_contents", type_="foreignkey")
    op.drop_constraint(None, "marketing_contents", type_="foreignkey")
    op.alter_column(
        "marketing_campaigns",
        "end_date",
        existing_type=sa.String(length=50),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "marketing_campaigns",
        "start_date",
        existing_type=sa.String(length=50),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_customers_phone"), table_name="customers")
    op.create_index(op.f("ix_customers_phone"), "customers", ["phone"], unique=False)
    op.create_index(op.f("ix_customers_status"), "customers", ["status"], unique=False)
    op.add_column(
        "ai_messages",
        sa.Column("metadata", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "ai_messages", type_="foreignkey")
    op.create_index(op.f("ix_ai_messages_role"), "ai_messages", ["role"], unique=False)
    op.drop_column("ai_messages", "extra_metadata")
    op.create_index(
        op.f("ix_ai_conversations_agent_type"),
        "ai_conversations",
        ["agent_type"],
        unique=False,
    )
    # ### end Alembic commands ###
