"""fix order module: remove circular fks, update numeric precision, rename sku

Revision ID: feb39ceece7d
Revises: f4a1b2c3d4e5
Create Date: 2026-09-17 10:57:41.795269
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'feb39ceece7d'
down_revision: str | None = 'f4a1b2c3d4e5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE payment_status AS ENUM ('pending', 'paid', 'failed', 'refunded')")
    op.execute("CREATE TYPE payment_method AS ENUM ('credit_card', 'debit_card', 'paypal', 'bank_transfer', 'cash')")
    op.drop_constraint(op.f('billing_addresses_order_id_key'), 'billing_addresses', type_='unique')
    op.drop_index(op.f('ix_billing_addresses_order_id'), table_name='billing_addresses')
    op.create_index(op.f('ix_billing_addresses_order_id'), 'billing_addresses', ['order_id'], unique=True)
    op.add_column('order_items', sa.Column('sku', sa.String(length=100), nullable=False))
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('order_items', 'total_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_column('order_items', 'product_sku')
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_orders_billing_address_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_shipping_address_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_constraint(op.f('orders_shipping_address_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_billing_address_id_fkey'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'billing_address_id')
    op.drop_column('orders', 'shipping_address_id')
    op.drop_constraint(op.f('shipping_addresses_order_id_key'), 'shipping_addresses', type_='unique')
    op.drop_index(op.f('ix_shipping_addresses_order_id'), table_name='shipping_addresses')
    op.create_index(op.f('ix_shipping_addresses_order_id'), 'shipping_addresses', ['order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipping_addresses_order_id'), table_name='shipping_addresses')
    op.create_index(op.f('ix_shipping_addresses_order_id'), 'shipping_addresses', ['order_id'], unique=False)
    op.create_unique_constraint(op.f('shipping_addresses_order_id_key'), 'shipping_addresses', ['order_id'], postgresql_nulls_not_distinct=False)
    op.add_column('orders', sa.Column('shipping_address_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('billing_address_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('orders_billing_address_id_fkey'), 'orders', 'billing_addresses', ['billing_address_id'], ['id'])
    op.create_foreign_key(op.f('orders_shipping_address_id_fkey'), 'orders', 'shipping_addresses', ['shipping_address_id'], ['id'])
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_shipping_address_id'), 'orders', ['shipping_address_id'], unique=False)
    op.create_index(op.f('ix_orders_billing_address_id'), 'orders', ['billing_address_id'], unique=False)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.add_column('order_items', sa.Column('product_sku', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('order_items', 'total_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('order_items', 'sku')
    op.drop_index(op.f('ix_billing_addresses_order_id'), table_name='billing_addresses')
    op.create_index(op.f('ix_billing_addresses_order_id'), 'billing_addresses', ['order_id'], unique=False)
    op.create_unique_constraint(op.f('billing_addresses_order_id_key'), 'billing_addresses', ['order_id'], postgresql_nulls_not_distinct=False)
    op.execute("DROP TYPE IF EXISTS payment_method")
    op.execute("DROP TYPE IF EXISTS payment_status")
    # ### end Alembic commands ###
